### PR TITLE
Added support for BrickletUVLight

### PR DESCRIPTION
**Pull request by jforge**

### CODE REVIEW

**Comment by photron** [comment]
Thanks!

**Comment by photron** [comment]
You named the JSON member "intensity". This doesn't match the documentation. If changed it to "uv_light" now.

**Comment by jforge** [comment]
Thanks for your fix.
I thought, this was OK because of the general docs online and in the generated python bindings, i.e. "Returns the UV light intensity of the sensor, the intensity is given in µW/cm²."

It's currently not 100% clear to me, which of the docs and sources should be used to derive the correct value-name for a getter specification. For me it was a reasonable physical name in this case. 
But I'm now aware of http://www.tinkerforge.com/en/doc/Software/Brick_MQTT_Proxy.html .

To avoid errors in the future, what is your expectation for new bricklet classes in the proxy? I will make an effort to be as accurate as possible, in most cases I would follow the guidelines and existing proxy classes.

**Comment by photron** [comment]
Yes, the names can be freely chosen in the MQTT proxy. But I'd like them to follow what we already use, because all parameters and return values in the protocol have names already. You can use the  [TCP/IP protocol documentation](http://www.tinkerforge.com/en/doc/Software/Bricklets/UVLight_Bricklet_TCPIP.html#BrickletUVLight.get_uv_light) as reference.

**Comment by jforge** [comment]
Ah, this is the one i missed. Yes, I also think, this documentation is the best naming reference.

**Pull request merged**
