### PR TITLE
Added support for BrickletCO2, BrickletRotaryEncoder, BrickletSegmentDisplay4x7, enhanced support for BrickletGPS, Fixed naming for Proxy classes

### PR DESCRIPTION
**Pull request by jforge**

### CODE REVIEW

**Comment by jforge** [comment]
For the BrickletGPS: I'm aware of the FIXME comment concerning the GPS bricklet, but an application using the proxy needs to evaluate the GPS status anyway; IMHO it's the job of the application subscribed to the GPS topics to put the data into the right context.

**Comment by photron** [comment]
You should not use callback for the BrickletRotaryEncoder in that way. I'll fix that, improve the documentation and explain how to handle the get_count function better.

**Comment by jforge** [comment]
Thanks, I really appreciate that. 
Does it need a complete refactoring or is the button callback OK? (taken from the joystick proxy)

**Comment by photron** [comment]
You should not use a callback for get_count at all. It's a getter. It doesn't fit into a GETTER_SPEC because of it's reset parameter. For such getters the update_extra_getters function was already there, but not used yet for any other Bricklet.

get_count is now called with False for the count topic and a new topic (_reset_count/set) was added to allow for resetting the count by calling get_count with True.

**Comment by jforge** [comment]
Thanks for your effort and the refactoring. This works like a charm and I think, I understand your requirements for a better integration.
If you are interested: I've created a small Node-RED flow + UI to test the bricklets co2, rotary encoder and segment display: https://gist.github.com/jforge/5ef35b695222962314e6d9f8e32ff7ad
(needs changing of the device ids and node-red contributions ui, splitter and json)

**Pull request merged**
